server.port=7070
server.host=localhost

# MongoDB Remote Verbindung
mongodb.host=ppr.lehre.texttechnologylab.org
mongodb.port=27020
mongodb.database=PPR_2025_227
mongodb.user=PPR_2025_227_rw
mongodb.password=sHPqeaJY
mongodb.authSource=PPR_2025_227