# Webserver
server.port=7070

# MongoDB Configuration
mongodb.user=admin
mongodb.password=password123
mongodb.host=mongodb
# Note: Inside the Docker network, Mongo runs on the default 27017 port. 
# The 27020 mapping is only for accessing it from outside Docker via a local GUI.
mongodb.port=27017 
mongodb.database=ppr_db
mongodb.authSource=admin